<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_txt</name>
   <tag></tag>
   <elementGuidId>d322c803-1a9e-42fe-8532-771e96356d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='q']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='q']</value>
      <webElementGuid>2c8b2840-493c-4483-9ad4-15e2c4c04faf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
